fix NullPointerException in chat server spawning
java.lang.NullPointerException: Cannot invoke
"java.util.Set.add(Object)" because
"vip.fubuki.playersync.sync.ChatSync.SocketList" is null