fix database setup without sophisticated backpack
Fixes SQLException:
java.sql.SQLSyntaxErrorException: Table 'playersync.backpack_data' doesn't exist

Fixes regression of 9ee7f9a95afd68192fcef920d79a2f3310446b73